/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import conector.MySqlConn;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lapiz
 */
public class Bajas extends javax.swing.JFrame {

    /**
     * Creates new form Bajas
     */
    public Bajas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
     MySqlConn conn=new MySqlConn();
     public Bajas(MySqlConn conn) {
        this.conn = conn;
         initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jButtonTickett = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Bajas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Salir");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel3.setText("No de Habitacion");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));
        getContentPane().add(jTextFieldNumero, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, 130, 30));

        jButtonTickett.setBackground(new java.awt.Color(255, 51, 51));
        jButtonTickett.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jButtonTickett.setForeground(new java.awt.Color(255, 255, 255));
        jButtonTickett.setText("Ticket");
        jButtonTickett.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTickettActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTickett, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 100, 30));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(347, 390, 110, 30));

        jLabel1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondo4.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-410, 0, 900, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonTickettActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTickettActionPerformed
        DefaultTableModel modelo = new DefaultTableModel();
            String nombre = null,telefono = null,origen = null,fechar = null,tiempo = null,nopersonas = null,tipoh,nohab;
            
            
            String numero = this.jTextFieldNumero.getText();
            String sql = "select * from huesped where no_hab = " + "' " +numero+ " '";
            
             conn.Consult(sql);
            try{
            String[] datos = new String[4];
                
            nombre = conn.rs.getString(1);   
            telefono = conn.rs.getString(2);
            origen = conn.rs.getString(3);
            fechar = conn.rs.getString(4);
            tiempo = conn.rs.getString(5);
            nopersonas = conn.rs.getString(6);
            tipoh = conn.rs.getString(7);
            nohab = conn.rs.getString(8);
           
            
           
            
            
            
               
            } catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Habitacion no valida/no en uso.");
                this.jTextFieldNumero.setText("");
            }
     //++++++++++++++++++++++++++++++++++++++++++++++++++++++++B A J A S +++++++++++++++++++++++++++++++++++++++++++++++++++++++++//
           String query = "DELETE FROM `huesped` WHERE no_hab = ' "+numero+" ' ";
           conn.Update(query);
     
     
    //+++++++++++++++++++++++++++++++++++++++++++++++++++++++++ P D F +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++//    
        Document documento = new Document();

        // Se crea el OutputStream para el fichero donde queremos dejar el pdf.
        FileOutputStream ficheroPdf = null;
        try {
            ficheroPdf = new FileOutputStream("C:\\Users\\lapiz\\OneDrive\\Escritorio\\TicketSalida.pdf");
        } catch (FileNotFoundException ex) {
            Logger.getLogger(RegistrarHuesped.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            // Se asocia el documento al OutputStream y se indica que el espaciado entre
            // lineas sera de 20. Esta llamada debe hacerse antes de abrir el documento
            PdfWriter.getInstance(documento,ficheroPdf).setInitialLeading(20);
        } catch (DocumentException ex) {
            Logger.getLogger(RegistrarHuesped.class.getName()).log(Level.SEVERE, null, ex);
        }

        // Se abre el documento.
        documento.open();
       
         
        try {
            documento.add(new Paragraph("    B O U C H E R  SALIDA  ",FontFactory.getFont("arial",22,Font.ITALIC,BaseColor.RED)));
            documento.add(new Paragraph(" "));
        } catch (DocumentException ex) {
            Logger.getLogger(RegistrarHuesped.class.getName()).log(Level.SEVERE, null, ex);
        }

        try { 
            
            documento.add(new Paragraph("Nombre: "+nombre));
            documento.add(new Paragraph("Número de Telefono: "+telefono));
            documento.add(new Paragraph("Ciudad de Origen: "+origen));
            String ferchar;
            documento.add(new Paragraph("Tipo de Habitación: "+fechar));
            documento.add(new Paragraph("Numero de Personas: "+nopersonas));
            documento.add(new Paragraph("Fecha de Ingreso: "+fechar));
            documento.add(new Paragraph("Tiempo de Hospedaje: "+tiempo));
            
            documento.add(new Paragraph("Total a pagar"+""));
            
        } catch (DocumentException ex) {
            Logger.getLogger(RegistrarHuesped.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        try
        {
                Image foto = Image.getInstance("C:\\Users\\lapiz\\OneDrive\\Escritorio\\Proyecto Final_ISC 4 B UAA\\src\\Imagenes\\Logo.png");
                foto.scaleToFit(100, 100);
                foto.setAlignment(Chunk.ALIGN_MIDDLE);
                documento.add(foto);
        }
        catch ( Exception e )
        {
        }
        try
        {
                Image foto = Image.getInstance("C:\\Users\\lapiz\\OneDrive\\Escritorio\\Proyecto Final_ISC 4 B UAA\\src\\Imagenes\\índice.jpg");
                foto.scaleToFit(100, 100);
                foto.setAlignment(Chunk.ALIGN_MIDDLE);
                documento.add(foto);
        }
        catch ( Exception e )
        {
        }
        JOptionPane.showMessageDialog(this, "Ticket generado en la ruta: \n C:\\Users\\lapiz\\OneDrive\\Escritorio\\TicketSalida.pd ");
       documento.close();
    }//GEN-LAST:event_jButtonTickettActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Consultas ventana = new Consultas();
        ventana.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bajas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Bajas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonTickett;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextFieldNumero;
    // End of variables declaration//GEN-END:variables
}
