/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import conector.MySqlConn;
import javax.swing.JOptionPane;

/**
 *
 * @author lapiz
 */
public class RegistrarHuesped extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarHuesped
     */
    MySqlConn conn=new MySqlConn();
    
    public RegistrarHuesped(MySqlConn conn) {
        this.conn = conn;
         initComponents();
        this.setLocationRelativeTo(null);
    }
    public RegistrarHuesped() {
        
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldNombreH = new javax.swing.JTextField();
        jTextFieldTelefonoH = new javax.swing.JTextField();
        jTextFieldDomicilioH = new javax.swing.JTextField();
        jTextFieldNacimientoH = new javax.swing.JTextField();
        jTextFieldCurpH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonRegistrarH = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("REGISTRAR HUESPED");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 150, -1, -1));

        jLabel3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel3.setText("Numero de telefono");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel4.setText("Domicilio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 230, -1, -1));

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel5.setText("Fecha de nacimiento");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, -1));

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel6.setText("Curp");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, -1, -1));

        jTextFieldNombreH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNombreHActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldNombreH, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, 260, 30));

        jTextFieldTelefonoH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefonoHActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldTelefonoH, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, 260, 30));

        jTextFieldDomicilioH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDomicilioHActionPerformed(evt);
            }
        });
        getContentPane().add(jTextFieldDomicilioH, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 220, 260, 30));
        getContentPane().add(jTextFieldNacimientoH, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 260, 30));
        getContentPane().add(jTextFieldCurpH, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 260, 30));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logomini.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 70, -1));

        jButtonRegistrarH.setBackground(new java.awt.Color(204, 0, 0));
        jButtonRegistrarH.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jButtonRegistrarH.setForeground(new java.awt.Color(255, 102, 0));
        jButtonRegistrarH.setText("Registrar");
        jButtonRegistrarH.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 102, 0)));
        jButtonRegistrarH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegistrarHActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonRegistrarH, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 100, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTelefonoHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefonoHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefonoHActionPerformed

    private void jTextFieldDomicilioHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDomicilioHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDomicilioHActionPerformed

    private void jTextFieldNombreHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNombreHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNombreHActionPerformed

    private void jButtonRegistrarHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegistrarHActionPerformed
    // TODO add your handling code here:
    String NombreH,NumT,Dom,FechaN,Curp,Id ;
    int id = 0;
    NombreH = this.jTextFieldNombreH.getText().trim();
    NumT = this.jTextFieldTelefonoH.getText().trim();
    Dom = this.jTextFieldDomicilioH.getText().trim();
    FechaN = this.jTextFieldNacimientoH.getText().trim();
    Curp = this.jTextFieldCurpH.getText().trim();
    id++;
    Id = String.valueOf(id);
            
        String part1="INSERT INTO `huesped` (`id`, `nombre`, `no_telefono`, `domicilio`, `fec_nac`, `curp`) VALUES ( " ;
        String part2=" ' "+Id+" ', '"+NombreH+" ', ' "+NumT+"  ', ' "+Dom+"  ', ' "+FechaN+"  ', ' "+Curp+" ' ); ";
        String query=part1+part2;
        int j=this.conn.Update(query);
        JOptionPane.showMessageDialog(this, "Huesped Registrado Correctamente "+NombreH);
        dispose();
    }//GEN-LAST:event_jButtonRegistrarHActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrarHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrarHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrarHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrarHuesped.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrarHuesped().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegistrarH;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField jTextFieldCurpH;
    private javax.swing.JTextField jTextFieldDomicilioH;
    private javax.swing.JTextField jTextFieldNacimientoH;
    private javax.swing.JTextField jTextFieldNombreH;
    private javax.swing.JTextField jTextFieldTelefonoH;
    // End of variables declaration//GEN-END:variables
}
