/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clases;

import conector.MySqlConn;
import javax.swing.JOptionPane;

/**
 *
 * @author nihil
 */
public class Vacantes extends javax.swing.JFrame {
    MySqlConn conn=new MySqlConn();
    /**
     * Creates new form Vacantes
     */
    public Vacantes (MySqlConn coon){
        initComponents();
        this.setLocationRelativeTo(null);
    }
    public Vacantes() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel_principal = new javax.swing.JPanel();
        jRadioButton_busquedaNom = new javax.swing.JRadioButton();
        jRadioButton_busquedaRep = new javax.swing.JRadioButton();
        jRadioButton_busquedaHab = new javax.swing.JRadioButton();
        jTextField_busquedaNom = new javax.swing.JTextField();
        jTextField_busquedaRep = new javax.swing.JTextField();
        jTextField_busquedaHab = new javax.swing.JTextField();
        jButton_siguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vacantes disponibles");

        jPanel_principal.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 0, 0)), "BUSQUEDA", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Castellar", 1, 13))); // NOI18N

        jRadioButton_busquedaNom.setText("Búsqueda por Nombre: ");
        jRadioButton_busquedaNom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_busquedaNomActionPerformed(evt);
            }
        });

        jRadioButton_busquedaRep.setText("Búsqueda por fecha de recepción:");
        jRadioButton_busquedaRep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_busquedaRepActionPerformed(evt);
            }
        });

        jRadioButton_busquedaHab.setText("Búsqueda por habitación:");
        jRadioButton_busquedaHab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton_busquedaHabActionPerformed(evt);
            }
        });

        jButton_siguiente.setBackground(new java.awt.Color(204, 0, 0));
        jButton_siguiente.setFont(new java.awt.Font("Castellar", 1, 18)); // NOI18N
        jButton_siguiente.setForeground(new java.awt.Color(255, 153, 0));
        jButton_siguiente.setText("SIGUIENTE");
        jButton_siguiente.setBorder(javax.swing.BorderFactory.createMatteBorder(4, 4, 4, 4, new java.awt.Color(255, 102, 0)));
        jButton_siguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_siguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_siguienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_principalLayout = new javax.swing.GroupLayout(jPanel_principal);
        jPanel_principal.setLayout(jPanel_principalLayout);
        jPanel_principalLayout.setHorizontalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel_principalLayout.createSequentialGroup()
                                .addComponent(jRadioButton_busquedaHab)
                                .addGap(53, 53, 53)
                                .addComponent(jTextField_busquedaHab))
                            .addGroup(jPanel_principalLayout.createSequentialGroup()
                                .addComponent(jRadioButton_busquedaRep)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_busquedaRep))
                            .addGroup(jPanel_principalLayout.createSequentialGroup()
                                .addComponent(jRadioButton_busquedaNom)
                                .addGap(58, 58, 58)
                                .addComponent(jTextField_busquedaNom, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel_principalLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jButton_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        jPanel_principalLayout.setVerticalGroup(
            jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_principalLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_busquedaNom)
                    .addComponent(jTextField_busquedaNom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_busquedaRep)
                    .addComponent(jTextField_busquedaRep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel_principalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton_busquedaHab)
                    .addComponent(jTextField_busquedaHab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jButton_siguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_siguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_siguienteActionPerformed
        // TODO add your handling code here:
         String nom,rep;
        int hab;
         int n=0;
         nom=this.jTextField_busquedaNom.getText().trim();
         rep=this.jTextField_busquedaRep.getText().trim();
         hab=Integer.parseInt(this.jTextField_busquedaHab.getText());
         if(!nom.isEmpty() || !rep.isEmpty() ){
          if (this.jRadioButton_busquedaNom.isSelected()) {
               String query = "SELECT * FROM `huesped` WHERE `nombre`= ' " + nom + " ' ";
            try {
                this.conn.rs.last();
                n = this.conn.rs.getRow();
                this.conn.rs.first();
            } catch (Exception ex) {
                System.out.println("Error 1");
            }
           /* Menu ventana=new Menu();
            ventana.setVisible(true);
            dispose();*/
       
        }
         if (this.jRadioButton_busquedaRep.isSelected()) {
     
         }
         if (this.jRadioButton_busquedaHab.isSelected()) {
            String query = "SELECT * FROM `habitaciones` WHERE `hab`= ' " + hab + " ' ";
            try {
                this.conn.rs.last();
                n = this.conn.rs.getRow();
                this.conn.rs.first();
            } catch (Exception ex) {
                System.out.println("Error 1");
            }
         }
         }else{
             JOptionPane.showMessageDialog(this, "Advertencia. Este campo no puede quedar vacio");
         }
    }//GEN-LAST:event_jButton_siguienteActionPerformed

    private void jRadioButton_busquedaNomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_busquedaNomActionPerformed
        // TODO add your handling code here:
           this.jTextField_busquedaHab.setEditable(false);
           this.jTextField_busquedaRep.setEditable(false);
           this.jTextField_busquedaNom.setEditable(true);
    }//GEN-LAST:event_jRadioButton_busquedaNomActionPerformed

    private void jRadioButton_busquedaRepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_busquedaRepActionPerformed
        // TODO add your handling code here:
           this.jTextField_busquedaHab.setEditable(false);
           this.jTextField_busquedaRep.setEditable(true);
           this.jTextField_busquedaNom.setEditable(false);
    }//GEN-LAST:event_jRadioButton_busquedaRepActionPerformed

    private void jRadioButton_busquedaHabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton_busquedaHabActionPerformed
        // TODO add your handling code here:
           this.jTextField_busquedaHab.setEditable(true);
           this.jTextField_busquedaRep.setEditable(false);
           this.jTextField_busquedaNom.setEditable(false);
    }//GEN-LAST:event_jRadioButton_busquedaHabActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vacantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vacantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vacantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vacantes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vacantes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_siguiente;
    private javax.swing.JPanel jPanel_principal;
    private javax.swing.JRadioButton jRadioButton_busquedaHab;
    private javax.swing.JRadioButton jRadioButton_busquedaNom;
    private javax.swing.JRadioButton jRadioButton_busquedaRep;
    private javax.swing.JTextField jTextField_busquedaHab;
    private javax.swing.JTextField jTextField_busquedaNom;
    private javax.swing.JTextField jTextField_busquedaRep;
    // End of variables declaration//GEN-END:variables
}
